### ISSUE TITLE
Issue running explainer

### ISSUE THREAD

**Issue by farahFif** [LarsHoldijk/RE-ParameterizedExplainerForGraphNeuralNetworks#5]
Hello, 
I tried the to run experiment_replication.ipynb, it seems that the stored models and the GNN model are different (check below the error). I also tried to retrain and replace the best_model in the other folder but the results don't match what's in the papers. 
Can you please help with this ?

Traceback (most recent call last):
  File "explain.py", line 19, in <module>
    (auc, auc_std), inf_time = replication(config.args.explainer, extension)
  File "/storage/RE-ParameterizedExplainerForGraphNeuralNetworks/ExplanationEvaluation/tasks/replication.py", line 158, in replication
    return_checkpoint=True)
  File "/storage/RE-ParameterizedExplainerForGraphNeuralNetworks/ExplanationEvaluation/models/model_selector.py", line 75, in model_selector
    model.load_state_dict(checkpoint['model_state_dict'])
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NodeGCN:
	Missing key(s) in state_dict: "conv1.lin.weight", "conv2.lin.weight", "conv3.lin.weight". 
	Unexpected key(s) in state_dict: "conv1.weight", "conv2.weight", "conv3.weight".

**Comment by farahFif** [comment]
Thanks to @seakkass solution,  model_selector needs to be updated when using pyg 2.0.4 to be able to use pre-trained models.
```
renamed_state_dict = {}
for key in checkpoint['model_state_dict']:
    if key.startswith('conv') and key.endswith('weight'):
        new_key = key[:5] + '.lin' + key[5:]
        renamed_state_dict[new_key] = (checkpoint['model_state_dict'][key]).T
    else:
        renamed_state_dict[key] = checkpoint['model_state_dict'][key]
model.load_state_dict(renamed_state_dict)
```
https://github.com/LarsHoldijk/RE-ParameterizedExplainerForGraphNeuralNetworks/issues/2#issue-1190422438
